config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  # Root
  root 'static_pages#index'
  match 'no_access' => 'static_pages#no_access', via: [:get]

  # Devise
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
  end

  # Resources
  resources :nations, except: [:show, :edit, :update, :destroy] do
    member do
      post 'reconnect'
      delete 'disconnect'
      post 'sync'
    end
  end

  resources :users, only: [:new, :create, :index, :destroy] do
    member do
      match 'approve' => 'users#approve', via: [:get, :put]
      put 'make_admin'
      match 'receive_notification' => 'users#receive_notification', via: [:put]
    end
    collection do
      get 'admins'
      match 'request_access' => 'users#request_access', via: [:get]
      match 'join' => 'users#join', via: [:post]
    end
  end

  resources :events, only: [:index] do
    # Events import
    collection do
      get 'imports'
      get 'imported'
      match 'imported/:id/logs' => 'events#logs', via: [:get], as: 'imported_log'
      post 'import', to: 'events#import'
    end
  end

  # Endpoints
  match '/endpoints/create_event', to: 'endpoints#create_event', via: :post

  # OAuth
  match ENV['OAUTH_REDIRECT_PATH'], to: 'nations#oauth', via: :get

end

app/models/user.rb
class User < ApplicationRecord

  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # ==
  # Associations
  # ==
  has_many :nations, dependent: :nullify

  # ==
  # Methods
  # ==
  def self.admin_users
    where(is_admin: true)
  end

  def self.users
    where(is_admin: false)
  end

  def self.admin_receive_notifications
    self.admin_users.where(receive_notifications: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin_user!, except: [:request_access, :join]
  before_action :set_user, only: [:destroy, :approve, :make_admin, :receive_notification]

  def index
    @users = User.users
  end

  def admins
    @users = User.admin_users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.is_admin = true
    @user.password = SecureRandom.base64 8
    @user.password_confirmation = @user.password

    if @user.save
      AdministratorInvitation.invite(@user.email, @user.password).deliver_now

      flash[:success] = 'User was successfully invited.'
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    nations = @user.nations.map {|nation| nation.slug}
    if @user.destroy
      nations.each do |nation|
        nation = Nation.find_by_slug(nation)
        nation.user_id = current_user.id
        nation.save
      end
      flash[:info] = 'User was successfully deleted.'
    else
      flash[:error] = 'User could not be deleted. Please try again.'
    end

    redirect_to users_path
  end

  def approve
    @user.is_approved = true
    @user.save

    if params[:code].present?
      AccessRequestsMailer.approved(@user.email, params[:code]).deliver_now
    end

    flash[:info] = "#{@user.email} was successfully approved."
    redirect_to users_path
  end

  def make_admin
    @user.is_admin = true
    @user.save

    flash[:info] = "#{@user.email} is now an admin."
    redirect_to users_path
  end

  def request_access
  end

  def join
    @user = User.new(email: params[:email])

    @user.password = SecureRandom.base64 8
    @user.password_confirmation = @user.password

    if @user.save
      admins = User.admin_receive_notifications
      admins.each do |admin|
        AccessRequestsMailer.approval(admin.email, @user.email, @user.password).deliver_now
      end
      flash[:success] = 'Your request was successfully sent for approval.'
    else
      flash[:success] = 'You have already requested access. Please wait for an admin to approve your request.'
    end
    redirect_to request_access_users_path
  end

  def receive_notification
    @user.update(user_params)
  end

  private
  def user_params
    params.require(:user).permit(:email, :is_approved, :receive_notifications)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_admin_user!
    unless authenticate_user! && current_user.is_admin?
      flash[:error] = 'Access forbidden.'
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admins.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>
        <%= fa_icon "user-secret" %> Administrators
        <%= link_to 'Invite administrator', new_user_path, class: 'btn btn-primary pull-right' %>
      </h3>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Email</th>
            <th>&nbsp;</th>
            <th>Receive notifications?</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= current_user.email %></td>
            <td><%= current_user.created_at.strftime('%d %B %Y') %></td>
            <td>
              <%= form_for current_user, :url => receive_notification_user_path(current_user), method: :put, remote: true do |f| %>
                <%= f.check_box :receive_notifications %> <span class="label label-success notif" style="display:none;">Saved</span>
              <% end %>
            </td>
          </tr>
          <% @users.each do |user| %>
            <% unless user == current_user %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.created_at.strftime('%d %B %Y') %></td>
                <td>
                  <%= form_for user, :url => receive_notification_user_path(user), method: :put, remote: true do |f| %>
                    <%= f.check_box :receive_notifications, { disabled: true } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

<script type="text/javascript">
  $(function() {
    $('form').on('change', 'input:checkbox', function () {
      $(this).submit();
      $('.notif').fadeIn('slow');
      $('.notif').fadeOut(3000);
    });
  });
</script>

app/views/users/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>
        <%= fa_icon 'user-circle' %> Users
        <%= link_to 'Invite user', new_user_invitation_path, class: 'btn btn-primary pull-right' %>
      </h3>
      
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Email</th>
          <th>Is approved?</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= user.is_approved ? 'Yes' : 'No' %></td>
              <td>
              <div class="btn-group pull-right">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <% if user.is_approved %>
                    <li><%= link_to 'Make Admin', make_admin_user_path(user), method: :put, data: { confirm: 'Are you sure?' } %></li>
                  <% else %>
                    <li><%= link_to 'Approve', approve_user_path(user), method: :put, data: { confirm: 'Are you sure?' } %></li>
                  <% end %>
                  
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= fa_icon 'user-secret' %> Invite new administrator</h3>
                </div>
                <div class="panel-body">
                  <fieldset>
                    <%= form_for(@user) do |f| %>
                        <%= render 'shared/error_messages', object: @user %>

                        <div class="form-group">
                          <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
                        </div>

                        <div class="form-group">
                          <%= f.submit 'Invite', class: 'btn btn-success btn-block' %>
                        </div>
                    <% end %>
                  </fieldset>
                  <%= link_to 'Back', :back, class: 'btn btn-default btn-block' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/request_access.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> <%= fa_icon 'lock' %> Request access</h3>
                </div>
                <div class="panel-body">
                  <fieldset>
                    <%= form_tag join_users_path, method: :post do |f| %>
                      
                      <div class="form-group">
                        <%= text_field_tag :email, nil, autofocus: true, class: 'form-control', placeholder: 'Email' %>
                      </div>

                      <div class="actions">
                        <%= submit_tag 'Send request', class: 'btn btn-success btn-block' %>
                      </div>
                    <% end %>
                  </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>