config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  # Root
  root 'static_pages#index'
  match 'no_access' => 'static_pages#no_access', via: [:get]

  # Devise
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
  end

  # Resources
  resources :nations, except: [:show, :edit, :update, :destroy] do
    member do
      post 'reconnect'
      delete 'disconnect'
      post 'sync'
    end
  end

  resources :users, only: [:new, :create, :index, :destroy] do
    member do
      match 'approve' => 'users#approve', via: [:get, :put]
      put 'make_admin'
      match 'receive_notification' => 'users#receive_notification', via: [:put]
    end
    collection do
      get 'admins'
      match 'request_access' => 'users#request_access', via: [:get]
      match 'join' => 'users#join', via: [:post]
    end
  end

  resources :events, only: [:index] do
    # Events import
    collection do
      get 'imports'
      get 'imported'
      match 'imported/:id/logs' => 'events#logs', via: [:get], as: 'imported_log'
      post 'import', to: 'events#import'
    end
  end

  # Endpoints
  match '/endpoints/create_event', to: 'endpoints#create_event', via: :post

  # OAuth
  match ENV['OAUTH_REDIRECT_PATH'], to: 'nations#oauth', via: :get

end

app/models/nation.rb
class Nation < ApplicationRecord

  # ==
  # Associations
  # ==
  belongs_to :user
  has_many :sites

  # ==
  # Validations
  # ==
  validates_presence_of :slug
  validates_uniqueness_of :slug

  # ==
  # Methods
  # ==
  def nation_belongs_to_user?(user)
    user.id == self.user_id
  end

  def get_site(site_id)
    self.sites.each do |site|
      if site.nb_site_id.eql?(site_id)
        return site
      end
    end

    nil
  end

  def is_connected_to_nb?
    !self.token.blank?
  end

  def delete_non_existing_sites(existing_site_ids)
    self.sites.each do |site|
      unless existing_site_ids.include?(site.nb_site_id)
        site.destroy
      end
    end
  end

end

app/controllers/nations_controller.rb
class NationsController < ApplicationController
  load_and_authorize_resource
  include NationsHelper, SyncHelper

  before_action :set_nation, only: [:reconnect, :disconnect, :sync]
  before_action :authenticate_user!

  def index
    @nations = Nation.all
  end

  def new
    @nation = current_user.nations.build
  end

  def create
    @nation = current_user.nations.build(nation_params)

    if @nation.save
      cookies[:nation_id] = { value: @nation.id, expires: 10.minutes.from_now }
      redirect_to nb_authenticate_url
    else
      render :new
    end
  end

  def sync
    if current_user.is_admin? || @nation.user.is_approved
      begin
        get_all_sites @nation
        EventsSyncJob.perform_later(@nation.id)

        flash[:success] = 'Nation is successfully synchronizing. Please allow a few minutes for the process to complete.'
      rescue NationBuilder::BaseError => e
        flash[:error] = construct_error_message e
      ensure
        redirect_to nations_path
      end
    else
      flash[:error] = 'Only approved users can initiate the synchronization process.'
      redirect_to nations_path
    end
  end

  def disconnect
    @nation.token = nil
    if @nation.save
      flash[:warning] = 'Nation was successfully disconnected from NationBuilder.'
    else
      flash[:error] = 'Could not disconnect that nation from NationBuilder'
    end

    redirect_to nations_path
  end

  def reconnect
    cookies[:nation_id] = { value: @nation.id, expires: 10.minutes.from_now }
    redirect_to nb_authenticate_url
  end

  def oauth
    @nation = Nation.find(cookies[:nation_id])
    @nation.token = nb_get_token(params[:code])

    if @nation.save
      flash[:notice] = 'Nation was successfully connected to NationBuilder.'
      redirect_to nations_path
    else
      flash[:error] = 'Something went wrong. Please try again.'
      redirect_to nations_path
    end
  end

  private
  def set_nation
    @nation = Nation.find(params[:id])
  end

  def nation_params
    params.require(:nation).permit(:slug, :token)
  end

  def construct_error_message(exception)
    json_message = JSON.parse exception.message

    error_message = json_message['slug'] ? "For site slug: #{json_message['slug']} - #{json_message['message']}" : json_message['message']
    validation_messages = json_message['validation_errors'] ? "\"#{json_message['validation_errors'].join(', ')}\"" : ''

    "An unexpected error occurred. Please try again. (#{error_message} #{validation_messages})".strip
  end
end

app/helpers/nations_helper.rb
module NationsHelper
  def nb_get_token(code)
    client = nb_oauth_client
    token = client.auth_code.get_token(code, redirect_uri: nb_oauth_redirect_uri)
    token.token
  end

  def nb_authenticate_url
    client = nb_oauth_client
    client.auth_code.authorize_url(redirect_uri: nb_oauth_redirect_uri)
  end

  private
  def nb_oauth_client
    OAuth2::Client.new(ENV['OAUTH_CLIENT_ID'], ENV['OAUTH_CLIENT_SECRET'], site: "https://#{@nation.slug}.nationbuilder.com")
  end

  def nb_oauth_redirect_uri
    default_url_options = Rails.application.config.action_mailer.default_url_options

    case Rails.env
    when 'development'
      "http://#{default_url_options[:host]}#{':' + default_url_options[:port].to_s if default_url_options[:port]}#{ENV['OAUTH_REDIRECT_PATH']}"
    when 'production'
      "https://#{ENV['APP_DOMAIN']}" + "#{ENV['OAUTH_REDIRECT_PATH']}"
    end
    
  end
end

app/views/nations/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <h4>How does this work?</h4>
        <p>All nations that have been connected to this app can configure any of their events to be cloned directly into the central <%= ENV['APP_NAME'] %> calendar. In order to set an event to be cloned, simply add the "<%= ENV['EVENT_PAGE_TAG'] %>" tag to that event where it appears in the source nation's control panel. By default the sync process runs each day to clone any new events tagged "<%= ENV['EVENT_PAGE_TAG'] %>" in the connected nations listed below.</p>
        <h4>Need to clone an event right away?</h4>
        <p>If you just added an event to your nation (or have just given the "<%= ENV['EVENT_PAGE_TAG'] %>" tag to an existing event) and want to clone it into the <%= ENV['APP_NAME'] %> calendar straight away (rather than waiting for the automatic daily sync) then please select the "synchronise now" action for the relevant nation below. This will run the cloning process straight away and add your new event(s) to the central <%= ENV['APP_NAME'] %> calendar.</p>
        <% unless current_user.is_admin? %>
          <P>Please note that "synchronise now" option will only appear for nations that  you have connected to this app.</p>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <h3>
        <%= fa_icon "refresh" %> Nations
        <%= link_to 'Add Nation', new_nation_path, class: 'btn btn-primary pull-right' %>
      </h3>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Slug</th>
          <th>Nation administrator</th>
          <th>Is connected?</th>
          <th>Actions</th>
        </tr>
        </thead>

        <tbody>
          <% @nations.each do |nation| %>
              <tr>
                <td><%= nation.slug %></td>
                <td><%= nation.user.email %></td>
                <td><%= nation.is_connected_to_nb? ? 'Yes' : 'No' %></td>
                <td>
                  <% if nation.nation_belongs_to_user?(current_user) || current_user.is_admin? %>
                      <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                          <% if nation.is_connected_to_nb? %>
                              <% if current_user.is_admin || nation.user.is_approved %>
                                <li><%= link_to 'Synchronise now', sync_nation_path(nation), method: :post, data: { execute: 'showOverlay' } %></li>
                              <li role="separator" class="divider"></li>
                              <% end %>
                              <li><%= link_to 'Disconnect Nation', disconnect_nation_path(nation), method: :delete, data: { confirm: 'Are you sure?' } %></li>
                          <% else %>
                              <li><%= link_to 'Reconnect Nation', reconnect_nation_path(nation), method: :post %></li>
                          <% end %>
                        </ul>
                      </div>
                  <% else %>
                      N/A
                  <% end %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/nations/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= fa_icon 'plug' %> Connect your nation</h3>
                </div>
                <div class="panel-body">
                  <fieldset>
					<%= form_for(@nation) do |f| %>
					    <%= render 'shared/error_messages', object: @nation %>

					    <div class="form-group">
					      <%= f.text_field :slug, autofocus: true, class: 'form-control', placeholder: 'Slug' %>
					    </div>
					    <div class="form-group">
					      <%= f.submit 'Add Nation', class: 'btn btn-success btn-block' %>
					      <%= link_to 'Back', nations_path, class: 'btn btn-default btn-block' %>
					    </div>
					<% end %>
                  </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>